language: php

php:
  - 7.2
  - 7.3

before_install:
  - cp .env.travis .env
  # Travis doesn't have imagick, but we don't need it for the tests
  # from https://github.com/composer/composer/issues/5900
  - composer config platform.ext-imagick '0'
  # Composer will say the package name is invalid but that's not important
  # This is just so that it updates the platform config in the lock file without updating any package
  - composer update ext-imagick --prefer-dist --no-interaction
  - php artisan key:generate
